MONGO = Import("common/base/mongo.lua")
PROXY = Import("common/base/proxy.lua")
NODE_MGR = Import("common/base/node_mgr.lua")
GATE_MGR = Import("common/base/gate_mgr.lua")
LOGIN_MGR = Import("app/login/loginMgr.lua")