PROXY = Import("common/base/proxy.lua")
DB_PROXY = Import("common/base/backer_proxy.lua")
MONGO = Import("common/base/mongo.lua")
DB = Import("app/backer/db.lua")
NODE_MGR = Import("common/base/node_mgr.lua")
